apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault-pvc
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
