apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
