apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-next-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
